language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer require php-coveralls/php-coveralls
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - php vendor/bin/php-coveralls -v